name-template: v$NEXT_PATCH_VERSION 🌈
categories:
  - title: 🚀 Features
    label: feat
  - title: 🐛 Bug Fixes
    label: fix
  - title: 💅🏻 Styles
    label: style
  - title: 🖥 Maintenance
    label: chore
change-template: '- $TITLE (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
